export const categories = [
  "Acción",
  "Aventura",
  "Estrategia",
  "Carreras",
  "Deportes",
  "Multijugador",
  "Sigilo",
  "Rol",
  "Plataformas",
  "Puzzle",
];

export const games = [
  {
    id: 1,
    title: "Fireboy and watergirl 2",
    price: 400,
    category: "Multijugador",
    img: "game-fireboy.png",
  },
  {
    id: 2,
    title: "Ludo Hero",
    price: 0,
    category: "Multijugador",
    img: "game-ludo-hero.png",
  },
  {
    id: 3,
    title: "Stickman Battle",
    price: 0,
    category: "Multijugador",
    img: "game-stickman-battle.png",
  },
  {
    id: 4,
    title: "Pinturillo 2",
    price: 0,
    category: "Multijugador",
    img: "game-pinturillo-2.png",
  },
  {
    id: 5,
    title: "Puppet Fight",
    price: 0,
    category: "Multijugador",
    img: "game-puppet-fight.png",
  },
  {
    id: 6,
    title: "Volley Random",
    price: 500,
    category: "Multijugador",
    img: "game-volleyboy-random.png",
  },
  {
    id: 7,
    title: "Stickman Archero Fight",
    price: 335,
    category: "Acción",
    img: "game-stickman-archero-fight.png",
  },
  {
    id: 8,
    title: "Astro Dud",
    price: 50,
    category: "Acción",
    img: "game-astro-dud.png",
  },
  {
    id: 9,
    title: "Pokemon Edición Rubí",
    price: 0,
    category: "Acción",
    img: "game-pockemon-rubi.png",
  },
  {
    id: 10,
    title: "Super Fighters",
    price: 200,
    category: "Acción",
    img: "game-super-fighters.png",
  },
  {
    id: 11,
    title: "Impostor",
    price: 130,
    category: "Acción",
    img: "game-impostor.png",
  },
  {
    id: 12,
    title: "Pokémon: Let's Go Pikachu",
    price: 0,
    category: "Acción",
    img: "game-pockemon-lets-go-pickachu.png",
  },
  {
    id: 13,
    title: "Copa del mundo 2022",
    price: 400,
    category: "Deportes",
    img: "game-copa-del-mundo-2022.png",
  },
  {
    id: 14,
    title: "Basketball Stars",
    price: 0,
    category: "Deportes",
    img: "game-basketball-stars.png",
  },
  {
    id: 15,
    title: "Tenis de Mesa 3D",
    price: 1200,
    category: "Deportes",
    img: "game-tenis-de-mesa-3d.png",
  },
  {
    id: 16,
    title: "Baseball Hero 2",
    price: 0,
    category: "Deportes",
    img: "game-baseball-hero-2.png",
  },
  {
    id: 17,
    title: "3D Free Kick",
    price: 0,
    category: "Deportes",
    img: "",
  },
  {
    id: 18,
    title: "SkiFree",
    price: 0,
    category: "Deportes",
    img: "game-skifree.png",
  },
];
